version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blackjack
    ports:
      - "3306:3306"
    networks:
      - my_network

  blackjack-app:
    build: .
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306", "--", "npm", "start"] 
 
    env_file:
      - env/app.env

    ports:
      - "8080:8080"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
