services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blackjack
    ports:
      - "3306:3306"
    networks:
      - my_network

  blackjack-app:
    build: .
    depends_on:
      - mysql
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_NAME: blackjack
    ports:
      - "8080:8080"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
