version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blackjack
    ports:
      - "3306:3306"  # Ermöglicht den externen Zugriff auf MySQL
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 1s
      retries: 100
      interval: 3s
      start_period: 3s


  blackjack-app:
    build: .
    depends_on:
      mysql:
        condition: service_healthy

    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: "mysql"  # Verweist auf die statische IP von MySQL
      DB_PORT: "3306"
      DB_NAME: blackjack
    ports:
      - "8080:8080"


